#!/usr/bin/env python3
"""build_spec_digest.py — generate views/spec-digest.md: one line per decision, requirement and spec section (REQ-049 AC-1, OD-69).

Usage:
    python tools/build_spec_digest.py [ROOT]            # write ROOT/views/spec-digest.md
    python tools/build_spec_digest.py [ROOT] --check    # exit 1 if that file is missing or stale

Read it before asking the owner anything: a lookup by meaning across the whole spec, where tools/spec_similar.py
only matches shared words. Lines:

- one per decision: id, date, the bold sentence it opens with (else its first sentence), and its relation cell. Read through
  tools/spec_text.py, the same readers spec_dupes uses: the Factory's docs/spec/decisions.md table rows and a
  project's spec/decisions/*.md records;
- one per requirement: id, status, title;
- one per spec section heading: docs/spec/00-master-handoff.md (the Factory's spec) and every other Markdown file
  under spec/ except the requirement and decision records (a project's spec sections).

Long cells are cut at a fixed length so the file stays small enough to read whole (the Factory's must stay under
24000 bytes; a test checks it). The file is generated: never edit it by hand, regenerate it.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import spec_text as st  # noqa: E402  (the one spec reader, REQ-009)

DIGEST_REL = Path("views") / "spec-digest.md"
HANDOFF_REL = "docs/spec/00-master-handoff.md"
SIZE_CAP = 24000
SENTENCE_MAX = 150
RELATION_MAX = 50
TITLE_MAX = 110
HEADING_MAX = 70
HEADING_LEVEL_MAX = 3
HEADER = ("<!-- generated by tools/build_spec_digest.py — do not edit by hand; regenerate with "
          "`python tools/build_spec_digest.py .` -->\n")

BOLD_RE = re.compile(r"^\*\*(.+?)\*\*")  # a LEAD bold span; mid-text emphasis is not the decision
FIRST_SENTENCE_RE = re.compile(r"^(.+?[.!?])(?:\s|$)")
MD_HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.+?)[ \t#]*$")


def one_line(text) -> str:
    return " ".join(str(text or "").split())


def cut(text: str, limit: int) -> str:
    text = one_line(text)
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def lead_sentence(text: str) -> str:
    """The bold span the text opens with, else the first sentence, else the whole text (one line)."""
    text = one_line(text)
    m = BOLD_RE.search(text)
    if m:
        return m.group(1).strip()
    m = FIRST_SENTENCE_RE.match(text)
    return m.group(1) if m else text


def decision_lines(src: st.Source) -> list[str]:
    out = []
    for rec in st.od_records(src):
        cells = st.od_cells(rec.raw)
        date = cells[1] if len(cells) > 1 else ""
        out.append(_decision_line(rec.id, date, rec.data.get("decision", ""), rec.data.get("changes", "")))
    for rec in st.adr_records(src):
        data = rec.data
        text = data.get("decision") or ""
        if not text:
            raw = src.read(rec.path) or ""
            _fm, body = st.split_frontmatter(raw)
            sentences = st.decision_sentences(body)
            text = sentences[0] if sentences else one_line(data.get("title"))
        out.append(_decision_line(rec.id, str(data.get("date") or ""), text, data.get("changes") or ""))
    return out


def _decision_line(rid: str, date: str, text: str, changes) -> str:
    line = f"- {rid} {one_line(date) or '—'}: {cut(lead_sentence(text), SENTENCE_MAX)}"
    rel = one_line(changes)
    if rel:
        line += f" [{cut(rel, RELATION_MAX)}]"
    return line


def requirement_lines(src: st.Source) -> list[str]:
    out = []
    for rec in st.requirement_records(src):
        status = one_line(rec.data.get("status")) or "—"
        out.append(f"- {rec.id} [{status}]: {cut(rec.data.get('title') or '', TITLE_MAX)}")
    return out


def _section_files(root: Path) -> list[str]:
    rels = []
    if (root / HANDOFF_REL).is_file():
        rels.append(HANDOFF_REL)
    spec = root / "spec"
    if spec.is_dir():
        skip = {st.REQ_DIR, st.ADR_DIR}
        # sort by the POSIX path text, never by Path: Windows compares Paths case-insensitively, Linux does not,
        # so a digest written on one OS read as stale on the other (spec/SPEC-DEVIATION.md vs spec/api/)
        for p in sorted(spec.rglob("*.md"), key=lambda q: q.relative_to(root).as_posix()):
            rel = p.relative_to(root).as_posix()
            if any(rel.startswith(s + "/") for s in skip):
                continue
            rels.append(rel)
    return rels


def section_lines(root: Path) -> list[str]:
    out = []
    for rel in _section_files(root):
        text = (root / rel).read_text(encoding="utf-8", errors="replace")
        heads, fence = [], None
        for line in text.splitlines():
            f = re.match(r"^[ \t]*(```+|~~~+)", line)
            if f:
                fence = None if fence and f.group(1)[0] == fence else (fence or f.group(1)[0])
                continue
            if fence:
                continue
            m = MD_HEADING_RE.match(line)
            if m and len(m.group(1)) <= HEADING_LEVEL_MAX:
                heads.append(f"- {'#' * len(m.group(1))} {cut(m.group(2), HEADING_MAX)}")
        if heads:
            out.append(f"\n### {rel}\n\n")
            out.append("\n".join(heads) + "\n")
    return out


def render(root: Path) -> str:
    src = st.Source(root)
    dec = decision_lines(src)
    req = requirement_lines(src)
    sec = section_lines(root)
    n_sec = sum(s.count("\n- ") + (1 if s.startswith("- ") else 0) for s in sec)
    out = [HEADER, "\n# Spec digest\n\n",
           "One line per decision, requirement and spec section. Read it before asking the owner anything; cite "
           "the ids you rely on in a `Spec basis:` line, or write `Spec basis: none (searched: <terms>)`.\n",
           f"\n## Decisions ({len(dec)})\n\n", ("\n".join(dec) + "\n") if dec else "_None._\n",
           f"\n## Requirements ({len(req)})\n\n", ("\n".join(req) + "\n") if req else "_None._\n",
           f"\n## Spec sections ({n_sec})\n"]
    out += sec if sec else ["\n_None._\n"]
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--check", action="store_true", help="exit 1 if views/spec-digest.md is missing or stale")
    args = ap.parse_args(argv)
    st.utf8_stdout()
    root = Path(args.root)
    expected = render(root)
    digest = root / DIGEST_REL
    if args.check:
        if not digest.is_file():
            print(f"build_spec_digest: {digest} is missing; run: python tools/build_spec_digest.py {args.root}")
            return 1
        if digest.read_bytes().decode("utf-8").replace("\r\n", "\n") != expected:
            print(f"build_spec_digest: {digest} is stale; run: python tools/build_spec_digest.py {args.root}")
            return 1
        print(f"build_spec_digest: {digest} is current")
        return 0
    digest.parent.mkdir(parents=True, exist_ok=True)
    digest.write_text(expected, encoding="utf-8", newline="\n")
    print(f"build_spec_digest: wrote {digest} ({len(expected.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
