#!/usr/bin/env python3
"""build_order.py — what may be built next, from the spec (REQ-006 AC-5/AC-6; owner decisions OD-33, OD-34).

Usage:
    python tools/build_order.py [ROOT]                     # write ROOT/views/build-order.md
    python tools/build_order.py [ROOT] --check             # exit 1 if that file is missing or stale
    python tools/build_order.py [ROOT] --may-start REQ-###  # may a work item for REQ-### start now?

Requirements at Verified, Reviewed, Released or Delivered-before-trace (REQ-014) are DONE; a Superseded
requirement is never listed, and a dependency on it follows superseded_by (a requirement: its status decides;
a decision: satisfied; a loop: a named failure). The rest are sorted topologically by
`depends_on` (a requirement never comes before one it depends on); among those ready at the same
point the tie-break is: walking skeleton first, then layer (core, foundation, feature, polish), then
`risk: high` first, then id. Order never comes from a score.

A requirement at Draft or Specified (any case) is recorded, not approved to build (REQ-036, OD-53): never
`next`, never in the order, listed apart under "Recorded, not approved to build", `--may-start` answers NO,
and an approved requirement that depends on one is `waiting` on it by id.

Each open requirement gets one state:
  next     every requirement it depends on is done;
  waiting  names the undone dependencies;
  blocked  a requirement it depends on, directly or transitively, is delivered by a work item with
           status `blocked` (parked): names that root requirement, the work item and its next_action.
           A requirement whose OWN work item is blocked is shown blocked too, naming that work item.

--may-start REQ-### exits 0 when that requirement is `next` and no requirement in an EARLIER group is
also `next` (groups in order: skeleton, then core+foundation, then feature, then polish). Otherwise it
exits 1 naming the earlier `next` items, the undone dependencies, or the blocking root. A work item
(not done or dropped) delivering the requirement may carry `order_override: <reason>`; it skips ONLY
the earlier-group check (never a done requirement, undone dependencies or a blocked chain), and
--may-start prints it, so every out-of-order start leaves its reason in the spec.
"""
from __future__ import annotations

import argparse
import heapq
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from factory_lint import parse_frontmatter  # noqa: E402  (one frontmatter parser for every tool)

VIEW_REL = Path("views") / "build-order.md"
DONE_STATUSES = ("Verified", "Reviewed", "Released", "Delivered-before-trace")  # REQ-014 AC-4
LAYER_ORDER = ("core", "foundation", "feature", "polish")
GROUP_NAMES = ("skeleton", "core+foundation", "feature", "polish", "no valid layer")
INACTIVE_WORK = ("done", "dropped")
UNAPPROVED_STATUSES = ("draft", "specified")  # REQ-036 / OD-53: recorded, not approved to build (compared lower-case)
UNAPPROVED_HEADING = "Recorded, not approved to build"

HEADER = ("<!-- generated by tools/build_order.py — do not edit by hand; regenerate with "
          "`python tools/build_order.py .` -->\n")


class Req:
    def __init__(self, rid: str, data: dict):
        self.id = rid
        self.title = str(data.get("title") or "")
        self.layer = data.get("layer") if isinstance(data.get("layer"), str) else ""
        self.risk = "high" if data.get("risk") == "high" else "normal"
        self.skeleton = data.get("skeleton") is True
        self.status = str(data.get("status") or "")
        deps = data.get("depends_on") or []
        self.depends_on = [d for d in deps if isinstance(d, str)] if isinstance(deps, list) else []
        # REQ-014: a Superseded requirement is never open (never `next`); a dependency on it follows superseded_by
        self.superseded = self.status == "Superseded"
        by = data.get("superseded_by")
        self.superseded_by = by.strip() if isinstance(by, str) else ""
        self.done = self.status in DONE_STATUSES or self.superseded
        # REQ-036: Draft / Specified is recorded, not approved; never next, never in the order to build
        self.unapproved = self.status.strip().lower() in UNAPPROVED_STATUSES and not self.done

    def key(self) -> tuple:
        layer_rank = LAYER_ORDER.index(self.layer) if self.layer in LAYER_ORDER else len(LAYER_ORDER)
        return (0 if self.skeleton else 1, layer_rank, 0 if self.risk == "high" else 1, self.id)

    def group(self) -> int:
        if self.skeleton:
            return 0
        if self.layer in ("core", "foundation"):
            return 1
        if self.layer == "feature":
            return 2
        if self.layer == "polish":
            return 3
        return 4


class Work:
    def __init__(self, wid: str, data: dict):
        self.id = wid
        rids = data.get("requirement_ids") or []
        self.requirement_ids = [r for r in rids if isinstance(r, str)] if isinstance(rids, list) else []
        self.status = str(data.get("status") or "")
        self.next_action = " ".join(str(data.get("next_action") or "").split())
        override = data.get("order_override")
        self.order_override = override.strip() if isinstance(override, str) else ""


def load(root: Path) -> tuple[dict[str, Req], list[Work]]:
    reqs: dict[str, Req] = {}
    req_dir = root / "spec" / "requirements"
    if req_dir.is_dir():
        for p in sorted(req_dir.glob("REQ-*.md")):
            data, err = parse_frontmatter(p)
            if err is None and isinstance(data, dict):
                rid = data.get("id") if isinstance(data.get("id"), str) else p.stem
                reqs[rid] = Req(rid, data)
    works: list[Work] = []
    work_dir = root / "work"
    if work_dir.is_dir():
        for p in sorted(work_dir.glob("W-*.md")):
            data, err = parse_frontmatter(p)
            if err is None and isinstance(data, dict):
                wid = data.get("id") if isinstance(data.get("id"), str) else p.stem
                works.append(Work(wid, data))
    resolve_superseded(reqs)
    return reqs, works


SUPERSEDED_ERRORS: list[str] = []   # filled by the last resolve_superseded(); printed and failing in main()


def resolve_superseded(reqs: dict[str, Req]) -> list[str]:
    """Rewrite each depends_on entry that names a Superseded requirement: follow superseded_by to the first
    requirement that is not Superseded (its own status then decides), or drop the entry when the chain ends at a
    decision (OD/ADR: satisfied). A loop is a named error; the dependency then stays unmet."""
    SUPERSEDED_ERRORS.clear()
    for r in reqs.values():
        new = []
        for d in r.depends_on:
            seen = [d]
            cur = d
            while cur in reqs and reqs[cur].superseded:
                nxt = reqs[cur].superseded_by
                if nxt in seen:
                    msg = f"superseded_by loop {' -> '.join(seen[seen.index(nxt):] + [nxt])}"
                    if msg not in SUPERSEDED_ERRORS:
                        SUPERSEDED_ERRORS.append(msg)
                    cur = f"{d} (superseded_by loop)"
                    break
                seen.append(nxt)
                cur = nxt
            if cur == r.id and d != r.id:
                msg = (f"{r.id} depends on {d}, which superseded_by resolves to {r.id} itself — a successor cannot "
                       f"wait on its predecessor; drop the dependency")
                if msg not in SUPERSEDED_ERRORS:
                    SUPERSEDED_ERRORS.append(msg)
                cur = f"{d} (superseded_by resolves to {r.id} itself)"
            if cur in reqs or cur.endswith(")") or cur.startswith("REQ-") or not cur:
                new.append(cur or f"{d} (superseded_by missing)")
            # else: the chain ends at a decision (OD-n / ADR-n): the dependency is satisfied
        r.depends_on = list(dict.fromkeys(new))
    return list(SUPERSEDED_ERRORS)


def _blocked_work(reqs: dict[str, Req], works: list[Work]) -> dict[str, list[Work]]:
    out: dict[str, list[Work]] = {}
    for w in works:
        if w.status == "blocked":
            for rid in w.requirement_ids:
                if rid in reqs:
                    out.setdefault(rid, []).append(w)
    return out


def _blocking_roots(rid: str, reqs: dict[str, Req], blocked: dict[str, list[Work]]) -> list[str]:
    """Undone requirements reachable from rid through depends_on (rid itself excluded) whose work
    item is blocked. Traversal stops at done requirements."""
    seen: set[str] = {rid}
    stack = list(reqs[rid].depends_on)
    roots: set[str] = set()
    while stack:
        cur = stack.pop()
        if cur in seen or cur not in reqs:
            continue
        seen.add(cur)
        if reqs[cur].done:
            continue
        if cur in blocked:
            roots.add(cur)
        stack.extend(reqs[cur].depends_on)
    return sorted(roots)


def _describe_blocked_root(root_id: str, blocked: dict[str, list[Work]]) -> str:
    parts = []
    for w in sorted(blocked[root_id], key=lambda w: w.id):
        parts.append(f"{w.id} blocked: {w.next_action or 'no next_action recorded'}")
    return f"{root_id} ({'; '.join(parts)})"


def _dep_label(d: str, reqs: dict[str, Req]) -> str:
    if d not in reqs:
        return f"{d} (no such requirement)"
    if reqs[d].unapproved:
        return f"{d} (recorded, not approved to build: status {reqs[d].status})"
    return d


def states(reqs: dict[str, Req], works: list[Work]) -> dict[str, tuple[str, str]]:
    """{open requirement id: (kind, full state text)}; kind in next / waiting / blocked."""
    blocked = _blocked_work(reqs, works)
    out: dict[str, tuple[str, str]] = {}
    for rid, r in reqs.items():
        if r.done or r.unapproved:
            continue
        if rid in blocked:
            own = "; ".join(f"{w.id} blocked: {w.next_action or 'no next_action recorded'}"
                            for w in sorted(blocked[rid], key=lambda w: w.id))
            out[rid] = ("blocked", f"blocked: its own work item {own}")
            continue
        roots = _blocking_roots(rid, reqs, blocked)
        if roots:
            out[rid] = ("blocked", "blocked: behind " + ", ".join(_describe_blocked_root(x, blocked) for x in roots))
            continue
        undone = sorted(d for d in r.depends_on if d not in reqs or not reqs[d].done)
        if undone:
            out[rid] = ("waiting", "waiting: on " + ", ".join(_dep_label(d, reqs) for d in undone))
            continue
        out[rid] = ("next", "next")
    return out


def order(reqs: dict[str, Req]) -> list[str]:
    """Open requirements, topologically by depends_on, ties by Req.key(). A cycle (factory_lint
    rejects one) cannot stall the sort: its members are appended in key order."""
    open_ids = {rid for rid, r in reqs.items() if not r.done and not r.unapproved}
    deps = {rid: {d for d in reqs[rid].depends_on if d in open_ids and d != rid} for rid in open_ids}
    users: dict[str, set[str]] = {rid: set() for rid in open_ids}
    for rid, ds in deps.items():
        for d in ds:
            users[d].add(rid)
    remaining = {rid: len(ds) for rid, ds in deps.items()}
    heap = [reqs[rid].key() for rid, n in remaining.items() if n == 0]
    heapq.heapify(heap)
    out: list[str] = []
    placed: set[str] = set()
    while heap:
        rid = heapq.heappop(heap)[-1]
        out.append(rid)
        placed.add(rid)
        for u in sorted(users[rid]):
            remaining[u] -= 1
            if remaining[u] == 0:
                heapq.heappush(heap, reqs[u].key())
    out.extend(sorted((rid for rid in open_ids if rid not in placed), key=lambda x: reqs[x].key()))
    return out


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def render(root: Path) -> str:
    reqs, works = load(root)
    st = states(reqs, works)
    done = sorted(rid for rid, r in reqs.items() if r.done and not r.superseded)
    gone = sorted(rid for rid, r in reqs.items() if r.superseded)
    recorded = sorted(rid for rid, r in reqs.items() if r.unapproved)
    lines = [
        HEADER,
        "# Build order",
        "",
        "What may be built next, generated from `spec/requirements/` and `work/`. Order: dependencies first "
        "(`depends_on`), then the walking skeleton, then layer (core, foundation, feature, polish), then "
        "`risk: high` first, then id. States: **next** (every dependency done), **waiting** (names the undone "
        "dependencies), **blocked** (a dependency, direct or transitive, is delivered by a blocked work item; "
        "names that root and its next_action). Ask before starting: `python tools/build_order.py . --may-start "
        "REQ-###`.",
        "",
        f"Done ({len(done)}): {', '.join(done) if done else 'none'}"
        + (f"; Superseded, never built ({len(gone)}): {', '.join(gone)}" if gone else ""),
        "",
        "| id | title | layer | risk | state |",
        "|---|---|---|---|---|",
    ]
    ordered = order(reqs)
    for rid in ordered:
        r = reqs[rid]
        layer = (r.layer or "(none)") + (", skeleton" if r.skeleton else "")
        lines.append(f"| {rid} | {_cell(r.title)} | {layer} | {r.risk} | {_cell(st[rid][1])} |")
    if not ordered:
        lines.append("")
        lines.append("_No open requirements._")
    lines += ["", f"## {UNAPPROVED_HEADING}", "",
              "Draft or Specified requirements are recorded only: never next, never in the order above. An approved "
              "requirement that depends on one shows as waiting on it by id.", ""]
    for rid in recorded:
        lines.append(f"- {rid} ({reqs[rid].status}): {_cell(reqs[rid].title)}")
    if not recorded:
        lines.append("_None._")
    return "\n".join(lines) + "\n"


def may_start(root: Path, rid: str) -> int:
    reqs, works = load(root)
    if rid not in reqs:
        print(f"may-start {rid}: NO — no such requirement under spec/requirements/")
        return 1
    r = reqs[rid]
    if r.done:
        print(f"may-start {rid}: NO — already done (status {r.status})")
        return 1
    if r.unapproved:
        print(f"may-start {rid}: NO — recorded, not approved to build (status {r.status})")
        return 1
    st = states(reqs, works)
    kind, text = st[rid]
    if kind != "next":
        print(f"may-start {rid}: NO — {text}")
        return 1
    earlier = sorted((x for x, (k, _t) in st.items() if k == "next" and reqs[x].group() < r.group()),
                     key=lambda x: reqs[x].key())
    overrides = [w for w in works
                 if rid in w.requirement_ids and w.order_override and w.status not in INACTIVE_WORK]
    if earlier and overrides:
        # The override skips ONLY this group-order check (REQ-006 AC-6).
        for w in overrides:
            print(f"may-start {rid}: YES by order_override on {w.id}: {w.order_override} "
                  f"(skips only the earlier-group check; earlier next: {', '.join(earlier)})")
        return 0
    if earlier:
        named = ", ".join(f"{x} ({GROUP_NAMES[reqs[x].group()]})" for x in earlier)
        print(f"may-start {rid}: NO — earlier-group requirements are next and come first "
              f"({rid} is {GROUP_NAMES[r.group()]}): {named}. To start anyway, the work item carries "
              f"order_override: <reason>")
        return 1
    print(f"may-start {rid}: YES — next, and no earlier-group requirement is next")
    return 0


def _safe_stdio() -> None:
    """Print UTF-8 with replacement, so a cp1252 pipe (Windows) never raises UnicodeEncodeError on a
    title or next_action containing a character outside that code page."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def main(argv: list[str] | None = None) -> int:
    _safe_stdio()
    ap = argparse.ArgumentParser(description="Generate or check views/build-order.md; gate a start.")
    ap.add_argument("root", nargs="?", default=".")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if views/build-order.md is missing or stale")
    mode.add_argument("--may-start", metavar="REQ_ID", help="exit 0 only if REQ_ID may start now")
    args = ap.parse_args(argv)
    root = Path(args.root)

    if args.may_start:
        rc = may_start(root, args.may_start)
        for e in SUPERSEDED_ERRORS:
            print(f"build_order: FAIL {e}")
        return 1 if SUPERSEDED_ERRORS else rc

    expected = render(root)
    view = root / VIEW_REL
    if SUPERSEDED_ERRORS:
        for e in SUPERSEDED_ERRORS:
            print(f"build_order: FAIL {e}")
        return 1
    if args.check:
        if not view.is_file():
            print(f"build_order: {view} is missing; run: python tools/build_order.py {args.root}")
            return 1
        current = view.read_bytes().decode("utf-8").replace("\r\n", "\n")
        if current != expected:
            print(f"build_order: {view} is stale; run: python tools/build_order.py {args.root}")
            return 1
        print(f"build_order: {view} is current")
        return 0
    view.parent.mkdir(parents=True, exist_ok=True)
    view.write_text(expected, encoding="utf-8", newline="\n")
    print(f"build_order: wrote {view}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
