#!/usr/bin/env python3
"""build_spec_index.py — generate spec/requirements/INDEX.md: requirements grouped by `section` (REQ-009 AC-1, OD-30).

Usage:
    python tools/build_spec_index.py [ROOT]            # write ROOT/spec/requirements/INDEX.md
    python tools/build_spec_index.py [ROOT] --check    # exit 1 if that file is missing or stale

One table per section (sections sorted by name), one row per requirement: id, title, layer, status. A requirement
with no `section` (factory_lint rejects it) is listed under "(no section)" so it is visible, never dropped. The file
is generated: never edit it by hand, regenerate it.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from factory_lint import parse_frontmatter  # noqa: E402  (one frontmatter parser for every tool)

INDEX_REL = Path("spec") / "requirements" / "INDEX.md"
NO_SECTION = "(no section)"
HEADER = ("<!-- generated by tools/build_spec_index.py — do not edit by hand; regenerate with "
          "`python tools/build_spec_index.py .` -->\n")


def cell(value) -> str:
    return " ".join(str(value or "").split()).replace("|", "\\|")


def collect(root: Path) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {}
    for p in sorted((root / "spec" / "requirements").glob("REQ-*.md")):
        data, err = parse_frontmatter(p)
        if err is not None or not isinstance(data, dict):
            data = {"id": p.stem, "title": f"(unreadable: {err})"}
        section = data.get("section")
        section = " ".join(section.split()) if isinstance(section, str) and section.strip() else NO_SECTION
        groups.setdefault(section, []).append(data)
    return groups


def render(root: Path) -> str:
    groups = collect(root)
    total = sum(len(v) for v in groups.values())
    out = [HEADER, "\n# Requirements by section\n\n",
           "Generated from `spec/requirements/REQ-*.md`, grouped by each requirement's `section`. Before writing a "
           "new requirement, find its section here and run `python tools/spec_similar.py . \"<text>\"`; extend or "
           "cite a match, never restate it.\n\n",
           f"Requirements: {total}; sections: {len([s for s in groups if s != NO_SECTION])}\n"]
    if not groups:
        out.append("\n_No requirements yet._\n")
    names = sorted((s for s in groups if s != NO_SECTION), key=str.lower)
    if NO_SECTION in groups:
        names.append(NO_SECTION)
    for name in names:
        rows = sorted(groups[name], key=lambda d: str(d.get("id", "")))
        out.append(f"\n## {name} ({len(rows)})\n\n| id | title | layer | status |\n|---|---|---|---|\n")
        for d in rows:
            out.append(f"| {cell(d.get('id'))} | {cell(d.get('title'))} | {cell(d.get('layer')) or '—'} | "
                       f"{cell(d.get('status')) or '—'} |\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--check", action="store_true", help="exit 1 if spec/requirements/INDEX.md is missing or stale")
    args = ap.parse_args(argv)
    root = Path(args.root)
    expected = render(root)
    index = root / INDEX_REL
    if args.check:
        if not index.is_file():
            print(f"build_spec_index: {index} is missing; run: python tools/build_spec_index.py {args.root}")
            return 1
        if index.read_bytes().decode("utf-8").replace("\r\n", "\n") != expected:
            print(f"build_spec_index: {index} is stale; run: python tools/build_spec_index.py {args.root}")
            return 1
        print(f"build_spec_index: {index} is current")
        return 0
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(expected, encoding="utf-8", newline="\n")
    print(f"build_spec_index: wrote {index}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
