#!/usr/bin/env python3
"""trace_check.py — checks that the requirement -> AC -> work item -> test -> evidence
chain is complete for every requirement in a Project OS tree, and can generate a
human-readable trace view.

Usage:
    python tools/trace_check.py ROOT [--strict] [--write-view] [--check-view]

For each requirement under ROOT/spec/requirements/REQ-###.md, checks:

  - it has at least one acceptance criterion (the schema already requires this, but a
    hand-broken file can still lack one; this check does not depend on the schema);
  - each acceptance criterion is named in the `tests_required` of at least one work
    item that links this requirement (an entry counts as naming AC-<n> when it is
    exactly "AC-<n>" or starts with "AC-<n>:");
  - that acceptance criterion has an evidence file at
    ROOT/evidence/<W-id>/<AC-id>.md (the work item that named it), with
    `result: pass` and a `verified_by` that is present and differs from `builder`
    (independent verification — the same agent cannot be both).

Separately, every work item's `requirement_ids` must each name a requirement that
actually exists under ROOT/spec/requirements/; a work item naming an unknown
requirement is reported as an orphan link and always fails the run.

Output: one line per requirement, `REQ-###: VERIFIED` or
`REQ-###: INCOMPLETE — <reason>; <reason>...`, plus one line per orphan work item link.

Exit code:
  - 1 if any orphan work-item link exists (a broken chain, always a hard failure);
  - 1 if --strict and any requirement is INCOMPLETE;
  - 1 if (without --strict) any requirement whose `status` is Verified, Reviewed, or
    Released is INCOMPLETE (a requirement not yet claimed done may be incomplete —
    that is normal, in-progress work, not a defect);
  - 1 if --check-view is given and views/trace.md is missing or does not match what
    --write-view would produce right now;
  - 0 otherwise.

--write-view writes ROOT/views/trace.md (generated — never hand-edit it).
--check-view exits 1 if that file would differ from a fresh generation.
"""
from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path
from typing import Any

AC_ID_RE = re.compile(r"^AC-\d+$")
REQ_ID_RE = re.compile(r"^REQ-\d{3,}$")
WORK_ID_RE = re.compile(r"^W-\d{3,}$")

DONE_STATUSES = {"Verified", "Reviewed", "Released"}

VIEW_HEADER = (
    "<!-- generated by tools/trace_check.py --write-view — do not edit by hand -->\n"
    "# Requirement trace view\n\n"
)


# frontmatter-parser-splits-on-any-triple-dash: a delimiter line is '---' alone on its
# line (trailing whitespace allowed), never a '---' substring inside a value.
_FRONTMATTER_DELIM_RE = re.compile(r"(?m)^---[ \t]*\r?$")


def parse_frontmatter(path: Path) -> tuple[dict[str, Any] | None, str | None]:
    """Minimal YAML-frontmatter parser: (data, error). Never raises."""
    try:
        import yaml
    except ImportError as exc:  # pragma: no cover
        return None, f"PyYAML not available: {exc}"

    try:
        text = path.read_text(encoding="utf-8")
    except Exception as exc:  # pragma: no cover
        return None, f"could not read file: {exc}"

    if not text.startswith("---"):
        return None, "missing YAML frontmatter"

    delims = list(_FRONTMATTER_DELIM_RE.finditer(text))
    if len(delims) < 2:
        return None, "malformed YAML frontmatter"

    try:
        data = yaml.safe_load(text[delims[0].end():delims[1].start()])
    except Exception as exc:
        return None, f"invalid YAML: {exc}"

    if data is None:
        data = {}
    if not isinstance(data, dict):
        return None, "frontmatter must be a YAML mapping"

    return data, None


def _names_ac(entry: str, ac_id: str) -> bool:
    entry = entry.strip()
    return entry == ac_id or entry.startswith(ac_id + ":")


class Requirement:
    def __init__(self, path: Path, data: dict[str, Any]):
        self.path = path
        self.data = data
        self.id: str = data.get("id", path.stem)
        self.status: str = data.get("status", "")
        acs = data.get("acceptance_criteria") or []
        self.ac_ids: list[str] = [
            ac["id"] for ac in acs if isinstance(ac, dict) and isinstance(ac.get("id"), str)
        ]


class WorkItem:
    def __init__(self, path: Path, data: dict[str, Any]):
        self.path = path
        self.data = data
        self.id: str = data.get("id", path.stem)
        self.requirement_ids: list[str] = [
            r for r in (data.get("requirement_ids") or []) if isinstance(r, str)
        ]
        self.tests_required: list[str] = [
            t for t in (data.get("tests_required") or []) if isinstance(t, str)
        ]

    def names_ac(self, ac_id: str) -> bool:
        return any(_names_ac(t, ac_id) for t in self.tests_required)


def load_requirements(root: Path) -> tuple[list[Requirement], list[str]]:
    req_dir = root / "spec" / "requirements"
    reqs: list[Requirement] = []
    parse_errors: list[str] = []
    if not req_dir.is_dir():
        return reqs, parse_errors
    for p in sorted(req_dir.glob("REQ-*.md")):
        data, err = parse_frontmatter(p)
        if err is not None:
            parse_errors.append(f"{p}: {err}")
            continue
        reqs.append(Requirement(p, data))
    return reqs, parse_errors


def load_work_items(root: Path) -> tuple[list[WorkItem], list[str]]:
    work_dir = root / "work"
    items: list[WorkItem] = []
    parse_errors: list[str] = []
    if not work_dir.is_dir():
        return items, parse_errors
    for p in sorted(work_dir.glob("W-*.md")):
        data, err = parse_frontmatter(p)
        if err is not None:
            parse_errors.append(f"{p}: {err}")
            continue
        items.append(WorkItem(p, data))
    return items, parse_errors


def load_evidence(root: Path, work_id: str, ac_id: str) -> tuple[dict[str, Any] | None, str | None]:
    ev_path = root / "evidence" / work_id / f"{ac_id}.md"
    if not ev_path.is_file():
        return None, "no evidence file"
    data, err = parse_frontmatter(ev_path)
    if err is not None:
        return None, f"evidence file unreadable: {err}"
    return data, None


def check_requirement(root: Path, req: Requirement, work_items: list[WorkItem]) -> list[str]:
    """Return a list of human-readable incompleteness reasons for one requirement
    (empty list means the requirement's whole chain is complete)."""
    reasons: list[str] = []

    if not req.ac_ids:
        reasons.append("no acceptance criteria")
        return reasons

    linked_items = [wi for wi in work_items if req.id in wi.requirement_ids]

    for ac_id in req.ac_ids:
        owning_items = [wi for wi in linked_items if wi.names_ac(ac_id)]
        if not owning_items:
            reasons.append(f"{ac_id} not named in any linked work item's tests_required")
            continue

        # An AC could in principle be named by more than one work item; it is complete
        # if at least one of them has valid, independently-verified, passing evidence.
        ac_ok = False
        ac_reason = None
        for wi in owning_items:
            data, err = load_evidence(root, wi.id, ac_id)
            if err is not None:
                ac_reason = f"{ac_id} {err} (work item {wi.id})"
                continue
            if data.get("ac") != ac_id:
                ac_reason = f"{ac_id} evidence file's ac field does not match ({wi.id})"
                continue
            if data.get("work_item") != wi.id:
                ac_reason = f"{ac_id} evidence file's work_item field does not match ({wi.id})"
                continue
            if data.get("result") != "pass":
                ac_reason = f"{ac_id} evidence result is not pass ({wi.id})"
                continue
            verified_by = data.get("verified_by")
            builder = data.get("builder")
            if not verified_by:
                ac_reason = f"{ac_id} evidence has no verified_by ({wi.id})"
                continue
            if builder and verified_by == builder:
                ac_reason = f"{ac_id} evidence verified_by matches builder — not independent ({wi.id})"
                continue
            ac_ok = True
            break

        if not ac_ok:
            reasons.append(ac_reason or f"{ac_id} incomplete")

    return reasons


def find_orphan_work_items(work_items: list[WorkItem], req_ids: set[str]) -> list[str]:
    orphans = []
    for wi in work_items:
        for rid in wi.requirement_ids:
            if rid not in req_ids:
                orphans.append(f"{wi.id}: ORPHAN — links unknown requirement {rid}")
    return orphans


def render_view(root: Path, req_lines: list[str], orphan_lines: list[str]) -> str:
    body = [VIEW_HEADER.rstrip("\n"), ""]
    body.append("## Requirements")
    body.append("")
    if req_lines:
        for line in req_lines:
            body.append(f"- {line}")
    else:
        body.append("- (no requirements found)")
    body.append("")
    body.append("## Orphan work-item links")
    body.append("")
    if orphan_lines:
        for line in orphan_lines:
            body.append(f"- {line}")
    else:
        body.append("- none")
    body.append("")
    return "\n".join(body)


def main(argv: list[str] | None = None) -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:  # pragma: no cover - not all stdout wrappers support this
        pass

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("root", help="Project OS root directory")
    parser.add_argument("--strict", action="store_true", help="Fail on any incomplete requirement, not just done ones")
    parser.add_argument("--write-view", action="store_true", help="Write ROOT/views/trace.md")
    parser.add_argument("--check-view", action="store_true", help="Exit 1 if ROOT/views/trace.md is stale or missing")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.is_dir():
        print(f"{args.root}: not a directory")
        return 1

    reqs, req_parse_errors = load_requirements(root)
    work_items, wi_parse_errors = load_work_items(root)

    for err in req_parse_errors + wi_parse_errors:
        print(f"PARSE ERROR: {err}")

    req_ids = {r.id for r in reqs}
    orphan_lines = find_orphan_work_items(work_items, req_ids)

    req_lines: list[str] = []
    any_incomplete = False
    any_done_incomplete = False

    for req in sorted(reqs, key=lambda r: r.id):
        reasons = check_requirement(root, req, work_items)
        if reasons:
            any_incomplete = True
            if req.status in DONE_STATUSES:
                any_done_incomplete = True
            req_lines.append(f"{req.id}: INCOMPLETE — " + "; ".join(reasons))
        else:
            req_lines.append(f"{req.id}: VERIFIED")

    for line in req_lines:
        print(line)
    for line in orphan_lines:
        print(line)

    exit_code = 0
    if orphan_lines or req_parse_errors or wi_parse_errors:
        exit_code = 1
    if args.strict and any_incomplete:
        exit_code = 1
    if any_done_incomplete:
        exit_code = 1

    if args.write_view or args.check_view:
        views_dir = root / "views"
        view_path = views_dir / "trace.md"
        expected = render_view(root, req_lines, orphan_lines)

        if args.check_view:
            if not view_path.is_file() or view_path.read_text(encoding="utf-8") != expected:
                print(f"{view_path}: stale or missing — run --write-view to regenerate")
                exit_code = 1

        if args.write_view:
            views_dir.mkdir(parents=True, exist_ok=True)
            view_path.write_text(expected, encoding="utf-8")

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
